# fly.toml app configuration file generated for veselovich-tg-app on 2023-07-20T13:35:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "veselovich-tg-app"
primary_region = "mia"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
