# fly.toml app configuration file generated for delicate-flower-722 on 2023-07-20T11:30:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-flower-722"
primary_region = "mia"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "flyio/hellofly:latest"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  port = 443
  handlers = ["http"]
[services.concurrency]
  hard_limit = 25
  soft_limit = 20
