app = "delicate-flower-722"
primary_region = "mia"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "flyio/hellofly:latest"
  cmd = "pip install -r requirements.txt && python main.py"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[services.concurrency]
  hard_limit = 25
  soft_limit = 20

[[services.ports]]
  handlers = ["http"]
  port = 5000